// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf3pwWATOEAwsd6TTtauRO4MHCcI6WGD4',
    appId: '1:427741528193:web:ad3a90a22a251ebce2cd80',
    messagingSenderId: '427741528193',
    projectId: 'werun-bf356',
    authDomain: 'werun-bf356.firebaseapp.com',
    databaseURL: 'https://werun-bf356-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'werun-bf356.firebasestorage.app',
    measurementId: 'G-688138L8KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6G4T6x8buiDJqDZmuAvuL_WBuWEYEm8U',
    appId: '1:427741528193:android:bb07a91925c8c445e2cd80',
    messagingSenderId: '427741528193',
    projectId: 'werun-bf356',
    databaseURL: 'https://werun-bf356-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'werun-bf356.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy41niEbT9IRbxsiXqBEjFJv5rPPgYGso',
    appId: '1:427741528193:ios:741e446236ba09a0e2cd80',
    messagingSenderId: '427741528193',
    projectId: 'werun-bf356',
    databaseURL: 'https://werun-bf356-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'werun-bf356.firebasestorage.app',
    iosBundleId: 'com.example.werunProjct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy41niEbT9IRbxsiXqBEjFJv5rPPgYGso',
    appId: '1:427741528193:ios:741e446236ba09a0e2cd80',
    messagingSenderId: '427741528193',
    projectId: 'werun-bf356',
    databaseURL: 'https://werun-bf356-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'werun-bf356.firebasestorage.app',
    iosBundleId: 'com.example.werunProjct',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf3pwWATOEAwsd6TTtauRO4MHCcI6WGD4',
    appId: '1:427741528193:web:7d50f5bc7580e4b8e2cd80',
    messagingSenderId: '427741528193',
    projectId: 'werun-bf356',
    authDomain: 'werun-bf356.firebaseapp.com',
    databaseURL: 'https://werun-bf356-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'werun-bf356.firebasestorage.app',
    measurementId: 'G-8F3RT23H9W',
  );
}
